name: Daily Yourshop Updates

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 KST 09:00 (UTC 00:00)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Node 환경 세팅
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 패키지 설치: package-lock.json이 있으면 npm ci, 없으면 npm i, 아예 없으면 스킵
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm i
          else
            echo "no package.json -> skip install"
          fi

      # Today Updates (있으면 실행, 없으면 스킵)
      - name: Build Today Updates (optional)
        run: |
          if [ -f scripts/build-today-updates.js ]; then
            node scripts/build-today-updates.js
          else
            echo "skip today-updates build"
          fi

      - name: Inject Today Updates (optional)
        run: |
          if [ -f scripts/inject-today-updates.js ]; then
            node scripts/inject-today-updates.js
          else
            echo "skip today-updates inject"
          fi

      # Product pages 생성 (data/products.json → p/*.md)
      - name: Generate product pages (Node)
        run: |
          if [ -f data/products.json ] && [ -f scripts/generate-pages.js ]; then
            if [ -f package.json ]; then
              npm run gen:pages
            else
              # package.json이 없어도 Node 단독 실행으로 지원
              node scripts/generate-pages.js
            fi
          else
            echo "missing data/products.json or scripts/generate-pages.js, skip"
          fi

      # Git 커밋/푸시 (변경 있을 때만)
      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Stage changes
        id: stage
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            echo "No changes to commit."
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge remote main
        if: steps.stage.outputs.no_changes == 'false'
        run: |
          git fetch origin main
          git merge --ff-only origin/main || git merge --no-edit origin/main

      - name: Commit and push
        if: steps.stage.outputs.no_changes == 'false'
        run: |
          git commit -m "chore: daily updates (today + product pages via Node)" || echo "Already committed"
          git push origin HEAD:main

      # 검색엔진 핑
      - name: Ping search engines
        run: |
          BASE='https://rkskqdl-a11y.github.io/yourshop'
          SITEMAP="$BASE/sitemap.xml"
          curl -s "https://www.google.com/ping?sitemap=$SITEMAP" || true
          curl -s "https://www.bing.com/ping?sitemap=$SITEMAP" || true
          curl -s "$BASE/" > /dev/null || true
