name: Daily Yourshop Updates

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 KST 09:00 (UTC 00:00)
  workflow_dispatch: {}   # 필요할 때 수동 실행도 가능

permissions:
  contents: write

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # scripts 폴더에 스크립트가 있다고 가정. 다음 단계에서 만들어줄 거야.
      - name: Install deps (optional)
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      - name: Generate Today Updates HTML
        run: |
          node scripts/build-today-updates.js

      - name: Inject Today Updates into homepage
        run: |
          node scripts/inject-today-updates.js

      - name: Commit changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@users.noreply.github.com'
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m 'chore: update today-updates section (automated)'
            git push
          else
            echo "No changes to commit."
          fi

      - name: Ping search engines
        run: |
          BASE='https://rkskqdl-a11y.github.io/yourshop'
          SITEMAP="$BASE/sitemap.xml"
          # Google/Bing 핑
          curl -s "https://www.google.com/ping?sitemap=$SITEMAP" || true
          curl -s "https://www.bing.com/ping?sitemap=$SITEMAP" || true
          # Naver는 공식 핑 엔드포인트가 없어 홈페이지를 직접 히트
          curl -s "$BASE/" > /dev/null || true
