name: Update Coupang Products

on:
  schedule:
    - cron: "0 0 * * *"   # 매일 00:00 UTC 실행 (한국은 오전 9시)
  workflow_dispatch:       # 필요시 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run script
        run: python -u fetch_products_seo.py
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}    # ← GitHub Secrets 참조
          SECRET_KEY: ${{ secrets.SECRET_KEY }}    # ← GitHub Secrets 참조
          COUNT: "30"         # 원하면 업로드 개수 제어
          DEBUG_LOG: "1"
    
      - name: Commit and push changes
        run: |
          set -e
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          echo "== git status =="
          git status --porcelain || true
          echo "== changed files =="
          git diff --name-only | sed -n '1,100p' || true
          git add index.html sitemap.xml robots.txt || true
          git commit -m "Auto-update products" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/rkskqdl-a11y/yourshop.git HEAD:main
