name: Update Coupang Products

on:
  schedule:
    - cron: "0 0 * * *"   # 매일 00:00 UTC 실행 (한국은 오전 9시)
  workflow_dispatch:       # 필요시 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run script
        run: python fetch_products_seo.py
        env:
          ACCESS_KEY: ${{ secrets.COUPANG_ACCESS }}
          SECRET_KEY: ${{ secrets.COUPANG_SECRET }}

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "Auto-update products" || echo "No changes to commit"
          git push
